service: sls-pg

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  vpc:
    securityGroupIds:
      - sg-0e567b68
    subnetIds:
      - subnet-0a053c6e
      - subnet-7a427e0c
      - subnet-95dfa5cd

functions:
  books-post-resource:
    handler: src/books/functions/post-resource.handler
    events:
      - http:
          path: books
          method: post
          cors: true

  books-get-collection:
    handler: src/books/functions/get-collection.handler
    events:
      - http:
          path: books
          method: get
          cors: true

  books-get-resource:
    handler: src/books/functions/get-resource.handler
    events:
      - http:
          path: books/{id}
          method: get
          cors: true

  books-put-resource:
    handler: src/books/functions/put-resource.handler
    events:
      - http:
          path: books/{id}
          method: put
          cors: true

  books-delete-resource:
    handler: src/books/functions/delete-resource.handler
    events:
      - http:
          path: books/{id}
          method: delete
          cors: true
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    port: ${env:OFFLINE_PORT}
